config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'relationships/follower'
  get 'relationships/followed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about", as: "about"

    resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
    resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  	end
  	get "search" => "searches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォローしている人一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followings
  end

  # フォローされている人一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
      <% if current_user != user %>
        <% if current_user.following?(user) %>
        <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
        <% end %>
      <% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>follows: <%= user.followings.count %></td>
        <td>followers: <%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>

        <% if current_user.id != user.id %>
        <td></td>
        <% else %>
        <% if current_user.following?(user) %>
        <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :DELETE %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
    <% end %>
  </tbody>
  <% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>follows: <%= user.followings.count %></td>
        <td>followers: <%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>

        <% if current_user.id != user.id %>
        <td></td>
        <% else %>
        <% if current_user.following?(user) %>
        <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :DELETE %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
    <% end %>
  </tbody>
  </table>
  <% else %>
  <p>ユーザーはいません</p>
<% end %>