config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'relationships/follower'
  get 'relationships/followed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about", as: "about"

    resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
    resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  	end
  	get "search" => "searches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_one_attached :profile_image
          has_many :books, dependent: :destroy
          has_many :favorites, dependent: :destroy
          has_many :post_comments, dependent: :destroy
          has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
          has_many :passive_relationships,class_name: "Relationship",foreign_key: "followed_id",dependent: :destroy

          has_many :followings, through: :active_relationships, source: :followed
          has_many :followers, through: :passive_relationships, source: :follower

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: { case_sensitive: false}
  validates :introduction, length: { maximum: 50 }



def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

    # フォローする
  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  # フォローを外す
  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  # すでにフォローしているのか確認
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
       @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<%= render 'searches/search' %>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>
        <td><%= link_to "Show", user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<%= image_tag user.get_profile_image(100,100) %>
<table class="table table-hover table-inverse">
  <thead>
   <tr>
	  <th>image</th>
	   <th><%= user.name %></th>
      </tr>
      <tr>
	    <th>introduction</th>
	   <th><%= user.introduction %></th>
   </tr>
   <tr>
      <th>フォロー数: <%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
   <tr>
      <th>フォロワー数: <%= link_to user.followers.count, user_followers_path(user.id) %></th>
   </tr>
  </thead>
</table>

<div class='row'>
        <% if current_user != user %>
        <% if current_user.following?(user) %>
        <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete %>
        <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
        <% end %>
      <% end %>
</div>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
    <% if @user.errors.any? %>
    <%= @user.errors.count %>error
      <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    <% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <h2>User info</h2>

    <%= form_with model:@user, local:true do |f| %>

      <%= render 'layouts/errors', obj: @user %>

      <div class="form-group">
        <%= f.label :Name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>

     <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>

      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control Introduction" %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'Update User' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>

<%= render 'books/form', user: @user, book: @book %>
</div>

<div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'index',users: @users, book: @book %>

</div>
  </div>
    </div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <div><%= flash[:notice] %></div>

      <h2>User info</h2>

      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>