config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'relationships/follower'
  get 'relationships/followed'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about", as: "about"

    resources :books, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
    resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  	end
  	get "search" => "searches#search"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
<div class="search_form">
  <%= form_with url:search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h1>Books search for "test"</h1>

<table class="table table-hover table-inverse">
  <% if @range == "User" %>
  <h2>Users search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(50, 50) %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>opinion</th>

      </tr>
    <tbody>
    <h2>Books search for "<%= @word %>"</h2>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image(50, 50) %>
          <% end %>
        </td>
        <td><%= link_to book.title , book_path(book.id) %></td>
        <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>
<p>Find me in app/views/searches/search.html.erb</p>